name: Build and publish docker images
on: 
  push:
    branches:
     - main
jobs:
  build-docker-images:
    runs-on: ubuntu-18.04
    env: 
      DOCKER_REPOSITORY: "omrisk"
    timeout-minutes: 45
    strategy:
      matrix:
        spark-version: [3.0.1, 3.0.2]
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2

      - name: Build docker images
        run: ./dev-scripts/builder.sh -a ${{ matrix.spark-version }}

      - name: Cache Docker images
        uses: satackey/action-docker-layer-caching@v0.0.11
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true
